source 'https://rubygems.org'
ruby '2.2.0'

gem 'sequel'
gem 'sequel_pg'
gem 'sinatra'
gem 'haml'
gem 'puma'
gem 'sinatra-flash'
gem 'sinatra-contrib'
gem 'bcrypt'
gem 'aws-sdk-v1'
gem 'bunny'
gem 'rack-ssl-enforcer'
gem 'mail'
gem "mini_magick"
